# NSE F&O Stock List (Futures and Options)
# Approximately 180-190 most liquid stocks

FNO_STOCKS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS", "HINDUNILVR.NS",
    "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS", "ITC.NS", "LT.NS", "AXISBANK.NS",
    "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS", "HCLTECH.NS", "WIPRO.NS",
    "ULTRACEMCO.NS", "TITAN.NS", "SUNPHARMA.NS", "NESTLEIND.NS", "POWERGRID.NS",
    "NTPC.NS", "TATAMOTORS.NS", "ONGC.NS", "M&M.NS", "TECHM.NS", "BAJAJFINSV.NS",
    "ADANIPORTS.NS", "COALINDIA.NS", "TATASTEEL.NS", "HINDALCO.NS", "INDUSINDBK.NS",
    "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BAJAJ-AUTO.NS", "GRASIM.NS", "JSWSTEEL.NS", "BRITANNIA.NS", "ADANIENT.NS",
    "APOLLOHOSP.NS", "BPCL.NS", "SHRIRAMFIN.NS", "TATACONSUM.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "VEDL.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "AMBUJACEM.NS",
    "ACC.NS", "ATGL.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BOSCHLTD.NS",
    "CHOLAFIN.NS", "COLPAL.NS", "DABUR.NS", "DLF.NS", "GODREJCP.NS", "GAIL.NS",
    "HAVELLS.NS", "ICICIPRULI.NS", "JINDALSTEL.NS", "MARICO.NS", "MCDOWELL-N.NS",
    "MOTHERSON.NS", "NAUKRI.NS", "ICICIGI.NS", "INDIGO.NS", "PIIND.NS",
    "PNB.NS", "PEL.NS", "PIDILITIND.NS", "SIEMENS.NS", "TORNTPHARM.NS", "TRENT.NS",
    "UPL.NS", "ZYDUSLIFE.NS", "IRCTC.NS", "SAIL.NS", "SRF.NS", "OFSS.NS",
    "PERSISTENT.NS", "LTIM.NS", "MPHASIS.NS", "COFORGE.NS", "L&TFH.NS", "PFC.NS",
    "RECLTD.NS", "CONCOR.NS", "LUPIN.NS", "BIOCON.NS", "ALKEM.NS", "IPCALAB.NS",
    "AUROPHARMA.NS", "BANDHANBNK.NS", "ABB.NS", "ABCAPITAL.NS", "ABFRL.NS",
    "ASTRAL.NS", "ATUL.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS", "AUBANK.NS",
    "BALKRISIND.NS", "BATAINDIA.NS", "BEL.NS", "BHARATFORG.NS", "CANBK.NS",
    "CUMMINSIND.NS", "DEEPAKNTR.NS", "DIXON.NS", "ESCORTS.NS", "EXIDEIND.NS",
    "FEDERALBNK.NS", "FORTIS.NS", "GNFC.NS", "GODREJPROP.NS", "GRAPHITE.NS",
    "HDFCAMC.NS", "HAL.NS", "IDEA.NS", "IDFCFIRSTB.NS", "INDHOTEL.NS",
    "INDUSTOWER.NS", "IOC.NS", "IRFC.NS", "JKCEMENT.NS", "JUBLFOOD.NS",
    "LICI.NS", "LODHA.NS", "MANAPPURAM.NS", "METROPOLIS.NS", "MGL.NS",
    "MUTHOOTFIN.NS", "NMDC.NS", "OBEROIRLTY.NS", "PAYTM.NS", "PETRONET.NS",
    "POLYCAB.NS", "PRESTIGE.NS", "RAMCOCEM.NS", "SHREECEM.NS", "SOLARINDS.NS",
    "TATACOMM.NS", "TATAELXSI.NS", "TATAPOWER.NS", "TIINDIA.NS", "TVSMOTOR.NS",
    "VOLTAS.NS", "ZOMATO.NS", "SYNGENE.NS", "BHEL.NS", "PETRONET.NS", "INDIACEM.NS",
    "GUJGASLTD.NS", "IGL.NS", "GLENMARK.NS", "NATIONALUM.NS", "GMRINFRA.NS",
    "CANFINHOME.NS", "M&MFIN.NS", "IBULHSGFIN.NS", "RELIANCE.NS", "TATAPOWER.NS",
    "VOLTAS.NS", "POLYCAB.NS", "ASHOKLEY.NS", "ZEEL.NS", "MCX.NS", "COROMANDEL.NS"
]

def get_fno_list():
    return FNO_STOCKS
