# Nifty 500 Stock List with Sectors
# Updated: February 2026

NIFTY_500_STOCKS = {
    # Nifty 50 - Large Cap
    "RELIANCE.NS": {"name": "Reliance Industries", "sector": "Energy"},
    "TCS.NS": {"name": "Tata Consultancy Services", "sector": "IT"},
    "HDFCBANK.NS": {"name": "HDFC Bank", "sector": "Banking"},
    "INFY.NS": {"name": "Infosys", "sector": "IT"},
    "ICICIBANK.NS": {"name": "ICICI Bank", "sector": "Banking"},
    "HINDUNILVR.NS": {"name": "Hindustan Unilever", "sector": "FMCG"},
    "SBIN.NS": {"name": "State Bank of India", "sector": "Banking"},
    "BHARTIARTL.NS": {"name": "Bharti Airtel", "sector": "Telecom"},
    "KOTAKBANK.NS": {"name": "Kotak Mahindra Bank", "sector": "Banking"},
    "ITC.NS": {"name": "ITC", "sector": "FMCG"},
    "LT.NS": {"name": "Larsen & Toubro", "sector": "Infrastructure"},
    "AXISBANK.NS": {"name": "Axis Bank", "sector": "Banking"},
    "BAJFINANCE.NS": {"name": "Bajaj Finance", "sector": "Finance"},
    "ASIANPAINT.NS": {"name": "Asian Paints", "sector": "Paints"},
    "MARUTI.NS": {"name": "Maruti Suzuki", "sector": "Auto"},
    "HCLTECH.NS": {"name": "HCL Technologies", "sector": "IT"},
    "WIPRO.NS": {"name": "Wipro", "sector": "IT"},
    "ULTRACEMCO.NS": {"name": "UltraTech Cement", "sector": "Cement"},
    "TITAN.NS": {"name": "Titan Company", "sector": "Consumer"},
    "SUNPHARMA.NS": {"name": "Sun Pharma", "sector": "Pharma"},
    "NESTLEIND.NS": {"name": "Nestle India", "sector": "FMCG"},
    "POWERGRID.NS": {"name": "Power Grid", "sector": "Power"},
    "NTPC.NS": {"name": "NTPC", "sector": "Power"},
    "TATAMOTORS.NS": {"name": "Tata Motors", "sector": "Auto"},
    "ONGC.NS": {"name": "ONGC", "sector": "Energy"},
    "M&M.NS": {"name": "Mahindra & Mahindra", "sector": "Auto"},
    "TECHM.NS": {"name": "Tech Mahindra", "sector": "IT"},
    "BAJAJFINSV.NS": {"name": "Bajaj Finserv", "sector": "Finance"},
    "ADANIPORTS.NS": {"name": "Adani Ports", "sector": "Infrastructure"},
    "COALINDIA.NS": {"name": "Coal India", "sector": "Mining"},
    "TATASTEEL.NS": {"name": "Tata Steel", "sector": "Metals"},
    "HINDALCO.NS": {"name": "Hindalco", "sector": "Metals"},
    "INDUSINDBK.NS": {"name": "IndusInd Bank", "sector": "Banking"},
    "CIPLA.NS": {"name": "Cipla", "sector": "Pharma"},
    "DRREDDY.NS": {"name": "Dr Reddy's Lab", "sector": "Pharma"},
    "DIVISLAB.NS": {"name": "Divi's Lab", "sector": "Pharma"},
    "EICHERMOT.NS": {"name": "Eicher Motors", "sector": "Auto"},
    "HEROMOTOCO.NS": {"name": "Hero MotoCorp", "sector": "Auto"},
    "BAJAJ-AUTO.NS": {"name": "Bajaj Auto", "sector": "Auto"},
    "GRASIM.NS": {"name": "Grasim Industries", "sector": "Cement"},
    "JSWSTEEL.NS": {"name": "JSW Steel", "sector": "Metals"},
    "BRITANNIA.NS": {"name": "Britannia", "sector": "FMCG"},
    "ADANIENT.NS": {"name": "Adani Enterprises", "sector": "Conglomerate"},
    "APOLLOHOSP.NS": {"name": "Apollo Hospitals", "sector": "Healthcare"},
    "BPCL.NS": {"name": "BPCL", "sector": "Energy"},
    "SHRIRAMFIN.NS": {"name": "Shriram Finance", "sector": "Finance"},
    "TATACONSUM.NS": {"name": "Tata Consumer", "sector": "FMCG"},
    "SBILIFE.NS": {"name": "SBI Life", "sector": "Insurance"},
    "HDFCLIFE.NS": {"name": "HDFC Life", "sector": "Insurance"},
    "VEDL.NS": {"name": "Vedanta", "sector": "Metals"},
    
    # Nifty Next 50 - Mid/Large Cap
    "ADANIGREEN.NS": {"name": "Adani Green Energy", "sector": "Power"},
    "ADANITRANS.NS": {"name": "Adani Transmission", "sector": "Power"},
    "AMBUJACEM.NS": {"name": "Ambuja Cements", "sector": "Cement"},
    "ACC.NS": {"name": "ACC", "sector": "Cement"},
    "ATGL.NS": {"name": "Adani Total Gas", "sector": "Gas"},
    "BANKBARODA.NS": {"name": "Bank of Baroda", "sector": "Banking"},
    "BERGEPAINT.NS": {"name": "Berger Paints", "sector": "Paints"},
    "BOSCHLTD.NS": {"name": "Bosch", "sector": "Auto"},
    "CHOLAFIN.NS": {"name": "Cholamandalam", "sector": "Finance"},
    "COLPAL.NS": {"name": "Colgate Palmolive", "sector": "FMCG"},
    "DABUR.NS": {"name": "Dabur", "sector": "FMCG"},
    "DLF.NS": {"name": "DLF", "sector": "Realty"},
    "GODREJCP.NS": {"name": "Godrej Consumer", "sector": "FMCG"},
    "GAIL.NS": {"name": "GAIL", "sector": "Gas"},
    "HAVELLS.NS": {"name": "Havells", "sector": "Electricals"},
    "ICICIPRULI.NS": {"name": "ICICI Pru Life", "sector": "Insurance"},
    "JINDALSTEL.NS": {"name": "Jindal Steel", "sector": "Metals"},
    "MARICO.NS": {"name": "Marico", "sector": "FMCG"},
    "MCDOWELL-N.NS": {"name": "United Spirits", "sector": "Beverages"},
    "MOTHERSON.NS": {"name": "Motherson Sumi", "sector": "Auto"},
    "NAUKRI.NS": {"name": "Naukri.com", "sector": "IT"},
    "ICICIGI.NS": {"name": "ICICI Lombard", "sector": "Insurance"},
    "INDIGO.NS": {"name": "IndiGo", "sector": "Aviation"},
    "PIIND.NS": {"name": "PI Industries", "sector": "Chemicals"},
    "PNB.NS": {"name": "Punjab National Bank", "sector": "Banking"},
    "PEL.NS": {"name": "Piramal Enterprises", "sector": "Finance"},
    "PIDILITIND.NS": {"name": "Pidilite", "sector": "Chemicals"},
    "SIEMENS.NS": {"name": "Siemens", "sector": "Industrials"},
    "TORNTPHARM.NS": {"name": "Torrent Pharma", "sector": "Pharma"},
    "TRENT.NS": {"name": "Trent", "sector": "Retail"},
    "UPL.NS": {"name": "UPL", "sector": "Agrochemicals"},
    "ZYDUSLIFE.NS": {"name": "Zydus Lifesciences", "sector": "Pharma"},
    "IRCTC.NS": {"name": "IRCTC", "sector": "Travel"},
    "SAIL.NS": {"name": "SAIL", "sector": "Metals"},
    "SRF.NS": {"name": "SRF", "sector": "Chemicals"},
    "OFSS.NS": {"name": "Oracle Financial", "sector": "IT"},
    "PERSISTENT.NS": {"name": "Persistent Systems", "sector": "IT"},
    "LTIM.NS": {"name": "LTIMindtree", "sector": "IT"},
    "MPHASIS.NS": {"name": "Mphasis", "sector": "IT"},
    "COFORGE.NS": {"name": "Coforge", "sector": "IT"},
    "L&TFH.NS": {"name": "L&T Finance", "sector": "Finance"},
    "PFC.NS": {"name": "Power Finance Corp", "sector": "Finance"},
    "RECLTD.NS": {"name": "REC", "sector": "Finance"},
    "CONCOR.NS": {"name": "Container Corp", "sector": "Logistics"},
    "LUPIN.NS": {"name": "Lupin", "sector": "Pharma"},
    "BIOCON.NS": {"name": "Biocon", "sector": "Pharma"},
    "ALKEM.NS": {"name": "Alkem Laboratories", "sector": "Pharma"},
    "IPCALAB.NS": {"name": "IPCA Laboratories", "sector": "Pharma"},
    "AUROPHARMA.NS": {"name": "Aurobindo Pharma", "sector": "Pharma"},
    "BANDHANBNK.NS": {"name": "Bandhan Bank", "sector": "Banking"},
    
    # Additional Top 100 Stocks
    "ABB.NS": {"name": "ABB India", "sector": "Industrials"},
    "ABCAPITAL.NS": {"name": "Aditya Birla Capital", "sector": "Finance"},
    "ABFRL.NS": {"name": "Aditya Birla Fashion", "sector": "Retail"},
    "ASTRAL.NS": {"name": "Astral", "sector": "Building Materials"},
    "ATUL.NS": {"name": "Atul", "sector": "Chemicals"},
    "APOLLOTYRE.NS": {"name": "Apollo Tyres", "sector": "Auto"},
    "ASHOKLEY.NS": {"name": "Ashok Leyland", "sector": "Auto"},
    "AUBANK.NS": {"name": "AU Small Finance Bank", "sector": "Banking"},
    "BALKRISIND.NS": {"name": "Balkrishna Industries", "sector": "Auto"},
    "BATAINDIA.NS": {"name": "Bata India", "sector": "Footwear"},
    "BEL.NS": {"name": "Bharat Electronics", "sector": "Defence"},
    "BHARATFORG.NS": {"name": "Bharat Forge", "sector": "Auto"},
    "CANBK.NS": {"name": "Canara Bank", "sector": "Banking"},
    "CUMMINSIND.NS": {"name": "Cummins India", "sector": "Auto"},
    "DEEPAKNTR.NS": {"name": "Deepak Nitrite", "sector": "Chemicals"},
    "DIXON.NS": {"name": "Dixon Technologies", "sector": "Electronics"},
    "ESCORTS.NS": {"name": "Escorts Kubota", "sector": "Auto"},
    "EXIDEIND.NS": {"name": "Exide Industries", "sector": "Auto"},
    "FEDERALBNK.NS": {"name": "Federal Bank", "sector": "Banking"},
    "FORTIS.NS": {"name": "Fortis Healthcare", "sector": "Healthcare"},
    "GNFC.NS": {"name": "Gujarat Narmada", "sector": "Chemicals"},
    "GODREJPROP.NS": {"name": "Godrej Properties", "sector": "Realty"},
    "GRAPHITE.NS": {"name": "Graphite India", "sector": "Industrials"},
    "HDFCAMC.NS": {"name": "HDFC AMC", "sector": "Finance"},
    "HAL.NS": {"name": "Hindustan Aeronautics", "sector": "Defence"},
    "IDEA.NS": {"name": "Vodafone Idea", "sector": "Telecom"},
    "IDFCFIRSTB.NS": {"name": "IDFC First Bank", "sector": "Banking"},
    "INDHOTEL.NS": {"name": "Indian Hotels", "sector": "Hospitality"},
    "INDUSTOWER.NS": {"name": "Indus Towers", "sector": "Telecom"},
    "IOC.NS": {"name": "Indian Oil", "sector": "Energy"},
    "IRFC.NS": {"name": "IRFC", "sector": "Finance"},
    "JKCEMENT.NS": {"name": "JK Cement", "sector": "Cement"},
    "JUBLFOOD.NS": {"name": "Jubilant FoodWorks", "sector": "Restaurant"},
    "LICI.NS": {"name": "LIC India", "sector": "Insurance"},
    "LODHA.NS": {"name": "Macrotech Developers", "sector": "Realty"},
    "MANAPPURAM.NS": {"name": "Manappuram Finance", "sector": "Finance"},
    "METROPOLIS.NS": {"name": "Metropolis Healthcare", "sector": "Healthcare"},
    "MGL.NS": {"name": "Mahanagar Gas", "sector": "Gas"},
    "MUTHOOTFIN.NS": {"name": "Muthoot Finance", "sector": "Finance"},
    "NMDC.NS": {"name": "NMDC", "sector": "Mining"},
    "OBEROIRLTY.NS": {"name": "Oberoi Realty", "sector": "Realty"},
    "PAYTM.NS": {"name": "Paytm", "sector": "Fintech"},
    "PETRONET.NS": {"name": "Petronet LNG", "sector": "Gas"},
    "POLYCAB.NS": {"name": "Polycab India", "sector": "Cables"},
    "PRESTIGE.NS": {"name": "Prestige Estates", "sector": "Realty"},
    "RAMCOCEM.NS": {"name": "Ramco Cements", "sector": "Cement"},
    "SHREECEM.NS": {"name": "Shree Cement", "sector": "Cement"},
    "SOLARINDS.NS": {"name": "Solar Industries", "sector": "Chemicals"},
    "TATACOMM.NS": {"name": "Tata Communications", "sector": "Telecom"},
    "TATAELXSI.NS": {"name": "Tata Elxsi", "sector": "IT"},
    "TATAPOWER.NS": {"name": "Tata Power", "sector": "Power"},
    "TIINDIA.NS": {"name": "Tube Investments", "sector": "Auto"},
    "TVSMOTOR.NS": {"name": "TVS Motor", "sector": "Auto"},
    "VOLTAS.NS": {"name": "Voltas", "sector": "Consumer"},
    "ZOMATO.NS": {"name": "Zomato", "sector": "Food Delivery"},
    
    # Additional 150 stocks from Nifty Midcap 150
    "AJANTPHARM.NS": {"name": "Ajanta Pharma", "sector": "Pharma"},
    "AMBER.NS": {"name": "Amber Enterprises", "sector": "Consumer"},
    "ANGELONE.NS": {"name": "Angel One", "sector": "Finance"},
    "APARINDS.NS": {"name": "Apar Industries", "sector": "Cables"},
    "APLAPOLLO.NS": {"name": "APL Apollo", "sector": "Steel"},
    "ARE&M.NS": {"name": "Amara Raja", "sector": "Auto"},
    "ASAHIINDIA.NS": {"name": "Asahi India", "sector": "Auto"},
    "ASTRAZEN.NS": {"name": "AstraZeneca", "sector": "Pharma"},
    "BAJAJHLDNG.NS": {"name": "Bajaj Holdings", "sector": "Finance"},
    "BASF.NS": {"name": "BASF India", "sector": "Chemicals"},
    "BAYERCROP.NS": {"name": "Bayer CropScience", "sector": "Agrochemicals"},
    "BHEL.NS": {"name": "BHEL", "sector": "Industrials"},
    "BIKAJI.NS": {"name": "Bikaji Foods", "sector": "FMCG"},
    "BIRLACORPN.NS": {"name": "Birla Corporation", "sector": "Cement"},
    "BLUEDART.NS": {"name": "Blue Dart", "sector": "Logistics"},
    "BSOFT.NS": {"name": "KPIT Technologies", "sector": "IT"},
    "CAMPUS.NS": {"name": "Campus Activewear", "sector": "Footwear"},
    "CELLO.NS": {"name": "Cello World", "sector": "Consumer"},
    "CENTURYPLY.NS": {"name": "Century Plyboards", "sector": "Building Materials"},
    "CESC.NS": {"name": "CESC", "sector": "Power"},
    "CHAMBLFERT.NS": {"name": "Chambal Fertilizers", "sector": "Fertilizers"},
    "CLEAN.NS": {"name": "Clean Science", "sector": "Chemicals"},
    "CROMPTON.NS": {"name": "Crompton Greaves", "sector": "Electricals"},
    "CRISIL.NS": {"name": "CRISIL", "sector": "Finance"},
    "DCM.NS": {"name": "DCM Shriram", "sector": "Agrochemicals"},
    "DELTACORP.NS": {"name": "Delta Corp", "sector": "Gaming"},
    "DEVYANI.NS": {"name": "Devyani International", "sector": "Restaurant"},
    "DALBHARAT.NS": {"name": "Dalmia Bharat", "sector": "Cement"},
    "EMAMILTD.NS": {"name": "Emami", "sector": "FMCG"},
    "ENDURANCE.NS": {"name": "Endurance Technologies", "sector": "Auto"},
    "FINEORG.NS": {"name": "Fine Organic", "sector": "Chemicals"},
    "FLUOROCHEM.NS": {"name": "Gujarat Fluoro", "sector": "Chemicals"},
    "GLENMARK.NS": {"name": "Glenmark Pharma", "sector": "Pharma"},
    "GMMPFAUDLR.NS": {"name": "GMM Pfaudler", "sector": "Chemicals"},
    "GESHIP.NS": {"name": "Great Eastern Shipping", "sector": "Shipping"},
    "GULFOILLUB.NS": {"name": "Gulf Oil", "sector": "Auto"},
    "HAPPSTMNDS.NS": {"name": "Happiest Minds", "sector": "IT"},
    "HATSUN.NS": {"name": "Hatsun Agro", "sector": "FMCG"},
    "HEIDELBERG.NS": {"name": "HeidelbergCement", "sector": "Cement"},
    "IIFL.NS": {"name": "IIFL Finance", "sector": "Finance"},
    "INDIANB.NS": {"name": "Indian Bank", "sector": "Banking"},
    "INOXWIND.NS": {"name": "Inox Wind", "sector": "Power"},
    "IRB.NS": {"name": "IRB Infrastructure", "sector": "Infrastructure"},
    "JBCHEPHARM.NS": {"name": "JB Chemicals", "sector": "Pharma"},
    "JKPAPER.NS": {"name": "JK Paper", "sector": "Paper"},
    "JKLAKSHMI.NS": {"name": "JK Lakshmi Cement", "sector": "Cement"},
    "JSWENERGY.NS": {"name": "JSW Energy", "sector": "Power"},
    "JYOTHYLAB.NS": {"name": "Jyothy Labs", "sector": "FMCG"},
    "KAJARIACER.NS": {"name": "Kajaria Ceramics", "sector": "Building Materials"},
    "KALYANKJIL.NS": {"name": "Kalyan Jewellers", "sector": "Retail"},
    "KEI.NS": {"name": "KEI Industries", "sector": "Cables"},
    "KSB.NS": {"name": "KSB", "sector": "Industrials"},
    "LAURUSLABS.NS": {"name": "Laurus Labs", "sector": "Pharma"},
    "LALPATHLAB.NS": {"name": "Dr Lal PathLabs", "sector": "Healthcare"},
    "LEMONTREE.NS": {"name": "Lemon Tree Hotels", "sector": "Hospitality"},
    "LICHSGFIN.NS": {"name": "LIC Housing Finance", "sector": "Finance"},
    "MASTEK.NS": {"name": "Mastek", "sector": "IT"},
    "MAXHEALTH.NS": {"name": "Max Healthcare", "sector": "Healthcare"},
    "MCX.NS": {"name": "MCX India", "sector": "Finance"},
    "MOTILALOFS.NS": {"name": "Motilal Oswal", "sector": "Finance"},
    "MRPL.NS": {"name": "MRPL", "sector": "Energy"},
    "NATCOPHARM.NS": {"name": "Natco Pharma", "sector": "Pharma"},
    "NAVINFLUOR.NS": {"name": "Navin Fluorine", "sector": "Chemicals"},
    "NH.NS": {"name": "Narayana Hrudayalaya", "sector": "Healthcare"},
    "NIPPON.NS": {"name": "Nippon Life AMC", "sector": "Finance"},
    "NLCINDIA.NS": {"name": "NLC India", "sector": "Power"},
    "ORIENTELEC.NS": {"name": "Orient Electric", "sector": "Electricals"},
    "PAGEIND.NS": {"name": "Page Industries", "sector": "Apparels"},
    "PATANJALI.NS": {"name": "Patanjali Foods", "sector": "FMCG"},
    "POLICYBZR.NS": {"name": "PB Fintech", "sector": "Fintech"},
    "POLYMED.NS": {"name": "Poly Medicure", "sector": "Healthcare"},
    "POONAWALLA.NS": {"name": "Poonawalla Fincorp", "sector": "Finance"},
    "PRAJIND.NS": {"name": "Praj Industries", "sector": "Industrials"},
    "PVRINOX.NS": {"name": "PVR INOX", "sector": "Entertainment"},
    "RAINBOW.NS": {"name": "Rainbow Hospitals", "sector": "Healthcare"},
    "RATNAMANI.NS": {"name": "Ratnamani Metals", "sector": "Steel"},
    "RELAXO.NS": {"name": "Relaxo Footwears", "sector": "Footwear"},
    "ROUTE.NS": {"name": "Route Mobile", "sector": "IT"},
    "SANOFI.NS": {"name": "Sanofi India", "sector": "Pharma"},
    "SCHAEFFLER.NS": {"name": "Schaeffler India", "sector": "Auto"},
    "SEQUENT.NS": {"name": "Sequent Scientific", "sector": "Pharma"},
    "SHOPERSTOP.NS": {"name": "Shoppers Stop", "sector": "Retail"},
    "SBICARD.NS": {"name": "SBI Card", "sector": "Finance"},
    "SKFINDIA.NS": {"name": "SKF India", "sector": "Auto"},
    "SONACOMS.NS": {"name": "Sona BLW", "sector": "Auto"},
    "SUNTV.NS": {"name": "Sun TV", "sector": "Media"},
    "SUPREMEIND.NS": {"name": "Supreme Industries", "sector": "Plastics"},
    "SWANENERGY.NS": {"name": "Swan Energy", "sector": "Textiles"},
    "SYMPHONY.NS": {"name": "Symphony", "sector": "Consumer"},
    "TASTYBITE.NS": {"name": "Tasty Bite", "sector": "FMCG"},
    "TATACHEM.NS": {"name": "Tata Chemicals", "sector": "Chemicals"},
    "TATAINVEST.NS": {"name": "Tata Investment", "sector": "Finance"},
    "TEAM.NS": {"name": "Teamlease Services", "sector": "HR Services"},
    "TIMKEN.NS": {"name": "Timken India", "sector": "Auto"},
    "TRITURBINE.NS": {"name": "Triveni Turbine", "sector": "Industrials"},
    "UJJIVAN.NS": {"name": "Ujjivan Small Finance", "sector": "Banking"},
    "UNIONBANK.NS": {"name": "Union Bank", "sector": "Banking"},
    "V-GUARD.NS": {"name": "V-Guard", "sector": "Electricals"},
    "VAIBHAVGBL.NS": {"name": "Vaibhav Global", "sector": "Retail"},
    "VBL.NS": {"name": "Varun Beverages", "sector": "Beverages"},
    "VIJAYA.NS": {"name": "Vijaya Diagnostic", "sector": "Healthcare"},
    "WELCORP.NS": {"name": "Welspun Corp", "sector": "Steel"},
    "WELENT.NS": {"name": "Welspun Enterprises", "sector": "Infrastructure"},
    "WESTLIFE.NS": {"name": "Westlife Foodworld", "sector": "Restaurant"},
    "WHIRLPOOL.NS": {"name": "Whirlpool India", "sector": "Consumer"},
    "YESBANK.NS": {"name": "Yes Bank", "sector": "Banking"},
    
    # Additional 250+ stocks from Nifty Smallcap 250
    "360ONE.NS": {"name": "360 ONE WAM", "sector": "Finance"},
    "5PAISA.NS": {"name": "5paisa Capital", "sector": "Finance"},
    "AARTIIND.NS": {"name": "Aarti Industries", "sector": "Chemicals"},
    "AARTIDRUGS.NS": {"name": "Aarti Drugs", "sector": "Pharma"},
    "ACE.NS": {"name": "Action Construction", "sector": "Industrials"},
    "ADANIENSOL.NS": {"name": "Adani Energy Solutions", "sector": "Power"},
    "ADANIPOWER.NS": {"name": "Adani Power", "sector": "Power"},
    "ADANIGAS.NS": {"name": "Adani Gas", "sector": "Gas"},
    "AFFLE.NS": {"name": "Affle India", "sector": "IT"},
    "AIAENG.NS": {"name": "AIA Engineering", "sector": "Industrials"},
    "ALKYLAMINE.NS": {"name": "Alkyl Amines", "sector": "Chemicals"},
    "ALLCARGO.NS": {"name": "Allcargo Logistics", "sector": "Logistics"},
    "AMARAJABAT.NS": {"name": "Amara Raja Energy", "sector": "Auto"},
    "ANANTRAJ.NS": {"name": "Anant Raj", "sector": "Realty"},
    "ANGELBRKG.NS": {"name": "Angel Broking", "sector": "Finance"},
    "ANURAS.NS": {"name": "Anupam Rasayan", "sector": "Chemicals"},
    "APTUS.NS": {"name": "Aptus Value Housing", "sector": "Finance"},
    "ARCHIES.NS": {"name": "Archies", "sector": "Retail"},
    "ARVINDFASN.NS": {"name": "Arvind Fashions", "sector": "Retail"},
    "ARVIND.NS": {"name": "Arvind Limited", "sector": "Textiles"},
    "ASIANHOTNR.NS": {"name": "Asian Hotels", "sector": "Hospitality"},
    "ASTRAZEN.NS": {"name": "AstraZeneca Pharma", "sector": "Pharma"},
    "ATUL.NS": {"name": "Atul Limited", "sector": "Chemicals"},
    "AUROPHARMA.NS": {"name": "Aurobindo Pharma", "sector": "Pharma"},
    "AVANTIFEED.NS": {"name": "Avanti Feeds", "sector": "Agriculture"},
    "AXISCADES.NS": {"name": "Axiscades Engineering", "sector": "IT"},
    "BBTC.NS": {"name": "Bombay Burmah", "sector": "Plantation"},
    "BCG.NS": {"name": "Brightcom Group", "sector": "IT"},
    "BEML.NS": {"name": "BEML", "sector": "Industrials"},
    "BLAL.NS": {"name": "BEML Land Assets", "sector": "Realty"},
    "BLUECHIP.NS": {"name": "Blue Chip India", "sector": "Finance"},
    "BPCL.NS": {"name": "Bharat Petroleum", "sector": "Energy"},
    "BSE.NS": {"name": "BSE", "sector": "Finance"},
    "CAPLIPOINT.NS": {"name": "Caplin Point", "sector": "Pharma"},
    "CARBORUNIV.NS": {"name": "Carborundum Universal", "sector": "Industrials"},
    "CEATLTD.NS": {"name": "CEAT", "sector": "Auto"},
    "CENTRAL.NS": {"name": "Central Bank", "sector": "Banking"},
    "CENTRUM.NS": {"name": "Centrum Capital", "sector": "Finance"},
    "CGPOWER.NS": {"name": "CG Power", "sector": "Industrials"},
    "CHALET.NS": {"name": "Chalet Hotels", "sector": "Hospitality"},
    "CHEMCON.NS": {"name": "Chemcon Speciality", "sector": "Chemicals"},
    "CHENNPETRO.NS": {"name": "Chennai Petroleum", "sector": "Energy"},
    "CITADEL.NS": {"name": "Citadel Realty", "sector": "Realty"},
    "CUB.NS": {"name": "City Union Bank", "sector": "Banking"},
    "COCHINSHIP.NS": {"name": "Cochin Shipyard", "sector": "Defence"},
    "COFFEEDAY.NS": {"name": "Coffee Day", "sector": "Restaurant"},
    "CONFIPET.NS": {"name": "Confidence Petroleum", "sector": "Energy"},
    "CRAFTSMAN.NS": {"name": "Craftsman Automation", "sector": "Auto"},
    "CREDITACC.NS": {"name": "CreditAccess Grameen", "sector": "Finance"},
    "CSB.NS": {"name": "CSB Bank", "sector": "Banking"},
    "CYIENT.NS": {"name": "Cyient", "sector": "IT"},
    "DCAL.NS": {"name": "Dishman Carbogen", "sector": "Pharma"},
    "DCMSHRIRAM.NS": {"name": "DCM Shriram", "sector": "Agrochemicals"},
    "DCXINDIA.NS": {"name": "DCX Systems", "sector": "Defence"},
    "DENORA.NS": {"name": "De Nora India", "sector": "Chemicals"},
    "DHANI.NS": {"name": "Dhani Services", "sector": "Finance"},
    "DHANUKA.NS": {"name": "Dhanuka Agritech", "sector": "Agrochemicals"},
    "DIAMONDYD.NS": {"name": "Prataap Snacks", "sector": "FMCG"},
    "DISHTV.NS": {"name": "Dish TV", "sector": "Media"},
    "DREDGECORP.NS": {"name": "Dredging Corporation", "sector": "Infrastructure"},
    "DWARKESH.NS": {"name": "Dwarikesh Sugar", "sector": "Sugar"},
    "ECLIPSE.NS": {"name": "Eclipse International", "sector": "Consumer"},
    "EDELWEISS.NS": {"name": "Edelweiss Financial", "sector": "Finance"},
    "EICHERMOT.NS": {"name": "Eicher Motors", "sector": "Auto"},
    "EIDPARRY.NS": {"name": "EID Parry", "sector": "Sugar"},
    "ELECTCAST.NS": {"name": "Electrosteel Castings", "sector": "Steel"},
    "ELECON.NS": {"name": "Elecon Engineering", "sector": "Industrials"},
    "ELGIEQUIP.NS": {"name": "Elgi Equipments", "sector": "Industrials"},
    "ESABINDIA.NS": {"name": "ESAB India", "sector": "Industrials"},
    "FCONSUMER.NS": {"name": "Future Consumer", "sector": "Retail"},
    "FIEMIND.NS": {"name": "Fiem Industries", "sector": "Auto"},
    "FINPIPE.NS": {"name": "Finolex Industries", "sector": "Cables"},
    "FINCABLES.NS": {"name": "Finolex Cables", "sector": "Cables"},
    "FLFL.NS": {"name": "Future Lifestyle", "sector": "Retail"},
    "GATEWAY.NS": {"name": "Gateway Distriparks", "sector": "Logistics"},
    "GEOJITFSL.NS": {"name": "Geojit Financial", "sector": "Finance"},
    "GET&D.NS": {"name": "GE T&D", "sector": "Industrials"},
    "GICRE.NS": {"name": "GIC Re", "sector": "Insurance"},
    "GILLETTE.NS": {"name": "Gillette India", "sector": "FMCG"},
    "GLAND.NS": {"name": "Gland Pharma", "sector": "Pharma"},
    "GLAXO.NS": {"name": "GlaxoSmithKline", "sector": "Pharma"},
    "GMRINFRA.NS": {"name": "GMR Infrastructure", "sector": "Infrastructure"},
    "GODFRYPHLP.NS": {"name": "Godfrey Phillips", "sector": "FMCG"},
    "GODIGIT.NS": {"name": "Go Digit Insurance", "sector": "Insurance"},
    "GPPL.NS": {"name": "Gujarat Pipavav", "sector": "Ports"},
    "GREENPLY.NS": {"name": "Greenply Industries", "sector": "Building Materials"},
    "GRINDWELL.NS": {"name": "Grindwell Norton", "sector": "Industrials"},
    "GRSE.NS": {"name": "GRSE", "sector": "Defence"},
    "GTLINFRA.NS": {"name": "GTL Infrastructure", "sector": "Telecom"},
    "GUJALKALI.NS": {"name": "Gujarat Alkalies", "sector": "Chemicals"},
    "GUJGASLTD.NS": {"name": "Gujarat Gas", "sector": "Gas"},
    "GUJSTATFIN.NS": {"name": "Gujarat State Fertilizer", "sector": "Fertilizers"},
    "HAPPSTMNDS.NS": {"name": "Happiest Minds", "sector": "IT"},
    "HATHWAY.NS": {"name": "Hathway Cable", "sector": "Media"},
    "HCC.NS": {"name": "HCC", "sector": "Infrastructure"},
    "HCG.NS": {"name": "HealthCare Global", "sector": "Healthcare"},
    "HEG.NS": {"name": "HEG", "sector": "Industrials"},
    "HERANBA.NS": {"name": "Heranba Industries", "sector": "Agrochemicals"},
    "HGS.NS": {"name": "Hinduja Global", "sector": "IT"},
    "HIKAL.NS": {"name": "Hikal", "sector": "Chemicals"},
    "HIL.NS": {"name": "HIL Limited", "sector": "Building Materials"},
    "HINDZINC.NS": {"name": "Hindustan Zinc", "sector": "Metals"},
    "HINDCOPPER.NS": {"name": "Hindustan Copper", "sector": "Metals"},
    "HINDPETRO.NS": {"name": "Hindustan Petroleum", "sector": "Energy"},
    "HMVL.NS": {"name": "Hindustan Media Ventures", "sector": "Media"},
    "HONAUT.NS": {"name": "Honeywell Automation", "sector": "Industrials"},
    "HUDCO.NS": {"name": "HUDCO", "sector": "Finance"},
    "IEX.NS": {"name": "Indian Energy Exchange", "sector": "Power"},
    "IFBIND.NS": {"name": "IFB Industries", "sector": "Consumer"},
    "IFCI.NS": {"name": "IFCI", "sector": "Finance"},
    "IGARASHI.NS": {"name": "Igarashi Motors", "sector": "Auto"},
    "IIFLWAM.NS": {"name": "IIFL Wealth", "sector": "Finance"},
    "IL&FSTRANS.NS": {"name": "IL&FS Transportation", "sector": "Infrastructure"},
    "INDBANK.NS": {"name": "Indusind Bank", "sector": "Banking"},
    "INDIACEM.NS": {"name": "India Cements", "sector": "Cement"},
    "INDIABULLS.NS": {"name": "Indiabulls Real Estate", "sector": "Realty"},
    "INDIANCARD.NS": {"name": "Indian Card Clothing", "sector": "Textiles"},
    "INDIANHUME.NS": {"name": "Indian Hume Pipe", "sector": "Building Materials"},
    "INDIGOPNTS.NS": {"name": "Indigo Paints", "sector": "Paints"},
    "INDNIPPON.NS": {"name": "India Nippon Electricals", "sector": "Electricals"},
    "INDOSTAR.NS": {"name": "IndoStar Capital", "sector": "Finance"},
    "INFIBEAM.NS": {"name": "Infibeam Avenues", "sector": "IT"},
    "INOXGREEN.NS": {"name": "Inox Green Energy", "sector": "Power"},
    "ISEC.NS": {"name": "ICICI Securities", "sector": "Finance"},
    "ITDCEM.NS": {"name": "ITD Cementation", "sector": "Infrastructure"},
    "IVC.NS": {"name": "IL&FS Investment", "sector": "Finance"},
    "J&KBANK.NS": {"name": "J&K Bank", "sector": "Banking"},
    "JAICORPLTD.NS": {"name": "Jaiprakash Associates", "sector": "Infrastructure"},
    "JAMNAAUTO.NS": {"name": "Jamna Auto", "sector": "Auto"},
    "JCHAC.NS": {"name": "Johnson Controls", "sector": "Auto"},
    "JKLAKSHMI.NS": {"name": "JK Lakshmi Cement", "sector": "Cement"},
    "JMFINANCIL.NS": {"name": "JM Financial", "sector": "Finance"},
    "JPASSOCIAT.NS": {"name": "Jaiprakash Power", "sector": "Power"},
    "JSL.NS": {"name": "Jindal Stainless", "sector": "Steel"},
    "JSLHISAR.NS": {"name": "Jindal Stainless Hisar", "sector": "Steel"},
    "JTEKTINDIA.NS": {"name": "JTEKT India", "sector": "Auto"},
    "JUSTDIAL.NS": {"name": "Just Dial", "sector": "IT"},
    "JYOTHYLAB.NS": {"name": "Jyothy Labs", "sector": "FMCG"},
    "KALPATPOWR.NS": {"name": "Kalpataru Projects", "sector": "Infrastructure"},
    "KANSAINER.NS": {"name": "Kansai Nerolac", "sector": "Paints"},
    "KCP.NS": {"name": "KCP Limited", "sector": "Cement"},
    "KECL.NS": {"name": "Kirloskar Electric", "sector": "Industrials"},
    "KIOCL.NS": {"name": "KIOCL", "sector": "Mining"},
    "KIRLFER.NS": {"name": "Kirloskar Ferrous", "sector": "Steel"},
    "KIRLOSBROS.NS": {"name": "Kirloskar Brothers", "sector": "Industrials"},
    "KIRLOSENG.NS": {"name": "Kirloskar Oil Engines", "sector": "Industrials"},
    "KPR.NS": {"name": "KPR Mill", "sector": "Textiles"},
    "KRBL.NS": {"name": "KRBL", "sector": "FMCG"},
    "KSL.NS": {"name": "Kalyani Steels", "sector": "Steel"},
    "KTKBANK.NS": {"name": "Karnataka Bank", "sector": "Banking"},
    "L&TFH.NS": {"name": "L&T Finance Holdings", "sector": "Finance"},
    "LATENTVIEW.NS": {"name": "LatentView Analytics", "sector": "IT"},
    "LGBBROSLTD.NS": {"name": "LG Balakrishnan", "sector": "Auto"},
    "LUMAXIND.NS": {"name": "Lumax Industries", "sector": "Auto"},
    "LUMAXTECH.NS": {"name": "Lumax Auto Tech", "sector": "Auto"},
    "MAHLIFE.NS": {"name": "Mahindra Lifespace", "sector": "Realty"},
    "MAHLOG.NS": {"name": "Mahindra Logistics", "sector": "Logistics"},
    "MAHSEAMLES.NS": {"name": "Maharashtra Seamless", "sector": "Steel"},
    "MAITHANALL.NS": {"name": "Maithan Alloys", "sector": "Metals"},
    "MANGL.NS": {"name": "Mangalam Cement", "sector": "Cement"},
    "MASFIN.NS": {"name": "MAS Financial", "sector": "Finance"},
    "MATRIMONY.NS": {"name": "Matrimony.com", "sector": "IT"},
    "MAZDA.NS": {"name": "Mazda Limited", "sector": "Auto"},
    "MEDPLUS.NS": {"name": "MedPlus Health", "sector": "Healthcare"},
    "MIDHANI.NS": {"name": "MIDHANI", "sector": "Defence"},
    "MINDACORP.NS": {"name": "Minda Corporation", "sector": "Auto"},
    "MINDAIND.NS": {"name": "Minda Industries", "sector": "Auto"},
    "MOIL.NS": {"name": "MOIL", "sector": "Mining"},
    "MONTECARLO.NS": {"name": "Monte Carlo Fashions", "sector": "Apparels"},
    "MRFDEV.NS": {"name": "MRF", "sector": "Auto"},
    "MSTCLTD.NS": {"name": "MSTC", "sector": "Trading"},
    "NATGEMIND.NS": {"name": "National Aluminium", "sector": "Metals"},
    "NBCC.NS": {"name": "NBCC India", "sector": "Infrastructure"},
    "NCC.NS": {"name": "NCC Limited", "sector": "Infrastructure"},
    "NECLIFE.NS": {"name": "Nectar Lifesciences", "sector": "Pharma"},
    "NELCO.NS": {"name": "Nelco", "sector": "IT"},
    "NETWORK18.NS": {"name": "Network18 Media", "sector": "Media"},
    "NEULANDLAB.NS": {"name": "Neuland Laboratories", "sector": "Pharma"},
    "NIACL.NS": {"name": "The New India Assurance", "sector": "Insurance"},
    "NRAIL.NS": {"name": "N R Agarwal", "sector": "Paper"},
    "NSLNISP.NS": {"name": "NMDC Steel", "sector": "Steel"},
    "NUCLEUS.NS": {"name": "Nucleus Software", "sector": "IT"},
    "OCCL.NS": {"name": "Oriental Carbon", "sector": "Chemicals"},
    "OIL.NS": {"name": "Oil India", "sector": "Energy"},
    "OMAXE.NS": {"name": "Omaxe", "sector": "Realty"},
    "ORIENTCEM.NS": {"name": "Orient Cement", "sector": "Cement"},
    "ORIENTHOT.NS": {"name": "Oriental Hotels", "sector": "Hospitality"},
    "ORIENTPPR.NS": {"name": "Orient Paper", "sector": "Paper"},
    "ORTINLAB.NS": {"name": "Orchid Pharma", "sector": "Pharma"},
    "PAEL.NS": {"name": "PAE Limited", "sector": "Textiles"},
    "PAISALO.NS": {"name": "Paisalo Digital", "sector": "Finance"},
    "PCJEWELLER.NS": {"name": "PC Jeweller", "sector": "Retail"},
    "PENIND.NS": {"name": "Pennar Industries", "sector": "Industrials"},
    "PGEL.NS": {"name": "PG Electroplast", "sector": "Electronics"},
    "PGHL.NS": {"name": "Procter & Gamble", "sector": "FMCG"},
    "PHILIPCARB.NS": {"name": "Phillips Carbon", "sector": "Chemicals"},
    "PHOENIXLTD.NS": {"name": "Phoenix Mills", "sector": "Realty"},
    "PRSMJOHNSN.NS": {"name": "Prism Johnson", "sector": "Cement"},
}

# Helper functions
def get_nifty_50_list():
    """Returns list of Nifty 50 stock symbols"""
    return list(NIFTY_500_STOCKS.keys())[:50]

def get_nifty_500_list():
    """Returns list of all Nifty 500 stock symbols"""
    return list(NIFTY_500_STOCKS.keys())

def get_stocks_by_sector(sector):
    """Returns stocks from a specific sector"""
    return [symbol for symbol, data in NIFTY_500_STOCKS.items() if data['sector'] == sector]

def get_all_sectors():
    """Returns list of all unique sectors"""
    return sorted(list(set(data['sector'] for data in NIFTY_500_STOCKS.values())))

def get_stock_info(symbol):
    """Returns stock information"""
    return NIFTY_500_STOCKS.get(symbol, None)

def get_large_cap_stocks():
    """Returns Nifty 50 stocks (first 50)"""
    return list(NIFTY_500_STOCKS.keys())[:50]

def get_mid_cap_stocks():
    """Returns stocks from position 51-250"""
    return list(NIFTY_500_STOCKS.keys())[50:250]

def get_small_cap_stocks():
    """Returns stocks from position 251-500"""
    return list(NIFTY_500_STOCKS.keys())[250:500]
